stages:
  - quality
  - deploy
.tags-default: &tags-default
  tags:
    - devops

.only-default: &only-default
  only:
    - dev

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.init_ssh_stg: &init_ssh_stg |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY_STG" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.init_ssh_prod: &init_ssh_prod |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

PHP Stan:
  image: nguyentruongson93/php:7.4.22
  stage: quality
  <<: *tags-default
  script:
    - git fetch origin
    - git branch
    - composer i
    - php -d memory_limit=1G /composer/vendor/bin/phpstan analyse core modules --level 1

dev:
  image: nguyentruongson93/php:7.4
  stage: deploy
  <<: *tags-default
  script:
    - *init_ssh
    - /composer/vendor/bin/envoy run deploy --server=dev --npm=prod
  only:
    - dev
  when: manual

staging:
  image: nguyentruongson93/php:7.4
  stage: deploy
  <<: *tags-default
  script:
    - *init_ssh_stg
    - /composer/vendor/bin/envoy run deploy --server=staging --npm=prod
  only:
    - staging
  when: manual

honban:
  image: nguyentruongson93/php:7.4
  stage: deploy
  <<: *tags-default
  script:
    - *init_ssh_prod
    - /composer/vendor/bin/envoy run deploy --server=prod --npm=prod
  when: manual
  only:
    - master
